package io.nosqlbench.paramodel.engine.compiler;

import io.nosqlbench.paramodel.compilation.CompilationContext;
import io.nosqlbench.paramodel.compilation.CompilationStage;
import io.nosqlbench.paramodel.elements.Element;
import io.nosqlbench.paramodel.engine.sequence.DefaultTrial;
import io.nosqlbench.paramodel.engine.sequence.DefaultValue;
import io.nosqlbench.paramodel.parameters.SamplingStrategy;
import io.nosqlbench.paramodel.plan.Axis;
import io.nosqlbench.paramodel.plan.TestPlan;
import io.nosqlbench.paramodel.sequence.Sequence;
import io.nosqlbench.paramodel.sequence.Trial;
import io.nosqlbench.paramodel.parameters.Value;

import java.time.Instant;
import java.util.*;

///
/// Stage 3: Trial Enumeration
///
/// Expands the parameter space into trials by computing the Cartesian product
/// of axis values, with support for:
///
/// - **Sampling strategies**: Grid (all values), Random (k samples), Linspace (n evenly-spaced)
/// - **Nesting order**: Controls which axis forms the outermost loop
/// - **Repetitions**: Duplicates each combination a specified number of times
/// - **Element-aware partitioning**: Axes targeting specific elements are grouped
///   per-element, with cross-element Cartesian composition
///
/// When axes declare a {@code targetElement} tag, the stage partitions them by
/// element, expands each element's axes independently, merges with the element's
/// {@link Element#configuration()} as base, and then composes cross-element
/// trials. Assignment keys use {@code "elementId.parameterName"} format.
///
/// Reads optional {@link SamplingConfig} from context. If absent, defaults to
/// Grid sampling for all axes in their natural order with no repetitions.
///
public class TrialEnumerationStage implements CompilationStage {
    public TrialEnumerationStage() {}

    @Override
    public String name() {
        return "TrialEnumeration";
    }

    @Override
    public void execute(CompilationContext context) {
        TestPlan plan = context.testPlan();
        List<Axis<?>> axes = plan.axes();

        // If the plan already has trials (pre-generated by adopter), use them
        if (plan instanceof Sequence seq && !seq.isEmpty()) {
            context.setTrials(seq.trials());
            context.recordMetric("trials_enumerated", seq.size());
            return;
        }

        // No axes = single trial with no varying parameters (degenerate Cartesian product).
        // This supports "one-shot" studies where all element parameters are fixed.
        if (axes.isEmpty()) {
            Trial.TrialMetadata metadata = new SimpleTrialMetadata(0, "default", "degenerate", 0);
            List<Trial> singleTrial = List.of(new DefaultTrial(
                UUID.randomUUID().toString(),
                Collections.emptyMap(),
                Collections.emptyList(),
                metadata
            ));
            context.setTrials(singleTrial);
            context.recordMetric("trials_enumerated", 1);
            return;
        }

        SamplingConfig config = context.get("samplingConfig")
            .map(SamplingConfig.class::cast)
            .orElse(SamplingConfig.defaults());

        // Partition axes by target element
        Map<String, List<Axis<?>>> axesByElement = new LinkedHashMap<>();
        List<Axis<?>> globalAxes = new ArrayList<>();
        for (Axis<?> axis : axes) {
            axis.targetElement().ifPresentOrElse(
                target -> axesByElement.computeIfAbsent(target, k -> new ArrayList<>()).add(axis),
                () -> globalAxes.add(axis)
            );
        }

        // If all axes are global (no targetElement), use existing global expansion
        if (axesByElement.isEmpty()) {
            List<Axis<?>> sortedAxes = new ArrayList<>(axes);
            sortedAxes.sort(Comparator.comparingInt(
                a -> config.nesting().getOrDefault(a.name(), axes.indexOf(a))));
            List<Trial> trials = generateGlobalTrials(sortedAxes, config);
            context.setTrials(trials);
            context.recordMetric("trials_enumerated", trials.size());
            return;
        }

        // Element-aware expansion
        List<Trial> trials = generateElementAwareTrials(axesByElement, globalAxes, plan, config);
        context.setTrials(trials);
        context.recordMetric("trials_enumerated", trials.size());
    }

    /// Generates trials using element-aware axis partitioning.
    ///
    /// 1. For each element with axes, expand its axes into binding sets
    /// 2. Merge with element.configuration() as base
    /// 3. Compose cross-element trials via Cartesian product
    /// 4. Qualify assignment keys with "elementId." prefix
    private List<Trial> generateElementAwareTrials(
            Map<String, List<Axis<?>>> axesByElement,
            List<Axis<?>> globalAxes,
            TestPlan plan,
            SamplingConfig config) {

        // Build per-element binding sets
        Map<String, List<Map<String, Object>>> elementBindingSets = new LinkedHashMap<>();

        for (var entry : axesByElement.entrySet()) {
            String elementId = entry.getKey();
            List<Axis<?>> elementAxes = entry.getValue();

            // Get base configuration from element
            Map<String, Object> baseConfig = plan.element(elementId)
                .map(Element::configuration)
                .orElse(Map.of());

            // Sort element axes by nesting
            List<Axis<?>> sortedElementAxes = new ArrayList<>(elementAxes);
            sortedElementAxes.sort(Comparator.comparingInt(
                a -> config.nesting().getOrDefault(a.name(), elementAxes.indexOf(a))));

            // Expand axes for this element
            List<Map<String, Object>> combinations = expandAxes(sortedElementAxes, config);

            // Merge base config into each combination (axis values override config)
            List<Map<String, Object>> merged = new ArrayList<>(combinations.size());
            for (Map<String, Object> combo : combinations) {
                Map<String, Object> m = new LinkedHashMap<>(baseConfig);
                m.putAll(combo);
                merged.add(m);
            }

            elementBindingSets.put(elementId, merged);
        }

        // Also expand global axes (not targeting any specific element)
        List<Map<String, Object>> globalCombinations;
        if (!globalAxes.isEmpty()) {
            List<Axis<?>> sortedGlobal = new ArrayList<>(globalAxes);
            sortedGlobal.sort(Comparator.comparingInt(
                a -> config.nesting().getOrDefault(a.name(), globalAxes.indexOf(a))));
            globalCombinations = expandAxes(sortedGlobal, config);
        } else {
            globalCombinations = List.of(Map.of());
        }

        // Compute max repetitions
        int maxRepetitions = computeMaxRepetitions(axesByElement, globalAxes, config);

        // Cross-element Cartesian product
        List<Map<String, Value<?>>> composedTrials = composeTrials(elementBindingSets, globalCombinations);

        // Apply repetitions
        if (maxRepetitions > 1) {
            List<Map<String, Value<?>>> repeated = new ArrayList<>(composedTrials.size() * maxRepetitions);
            for (Map<String, Value<?>> trial : composedTrials) {
                for (int r = 0; r < maxRepetitions; r++) {
                    repeated.add(trial);
                }
            }
            composedTrials = repeated;
        }

        // Wrap as Trial objects
        List<Trial> result = new ArrayList<>(composedTrials.size());
        int index = 0;
        for (Map<String, Value<?>> assignments : composedTrials) {
            String genMethod = maxRepetitions > 1
                ? "element_aware_rep" + (index % maxRepetitions)
                : "element_aware";
            Trial.TrialMetadata metadata = new SimpleTrialMetadata(index++, "default", genMethod, 0);
            result.add(new DefaultTrial(
                UUID.randomUUID().toString(),
                assignments,
                Collections.emptyList(),
                metadata
            ));
        }

        return result;
    }

    /// Composes cross-element binding sets into a single set of trial assignments.
    /// Assignment keys are qualified as "elementId.parameterName".
    private List<Map<String, Value<?>>> composeTrials(
            Map<String, List<Map<String, Object>>> elementBindingSets,
            List<Map<String, Object>> globalCombinations) {

        // Start with global combinations
        List<Map<String, Value<?>>> result = new ArrayList<>();
        for (Map<String, Object> global : globalCombinations) {
            Map<String, Value<?>> base = new LinkedHashMap<>();
            for (var e : global.entrySet()) {
                base.put(e.getKey(), new DefaultValue<>(
                    e.getValue(), e.getKey(), Instant.now(), Optional.of("Global axis")));
            }
            result.add(base);
        }
        if (result.isEmpty()) {
            result.add(new LinkedHashMap<>());
        }

        // Cross with each element's binding sets
        for (var entry : elementBindingSets.entrySet()) {
            String elementId = entry.getKey();
            List<Map<String, Object>> bindings = entry.getValue();

            List<Map<String, Value<?>>> expanded = new ArrayList<>();
            for (Map<String, Value<?>> existing : result) {
                for (Map<String, Object> binding : bindings) {
                    Map<String, Value<?>> combined = new LinkedHashMap<>(existing);
                    for (var be : binding.entrySet()) {
                        String qualifiedKey = elementId + "." + be.getKey();
                        combined.put(qualifiedKey, new DefaultValue<>(
                            be.getValue(), qualifiedKey, Instant.now(),
                            Optional.of("Element " + elementId)));
                    }
                    expanded.add(combined);
                }
            }
            result = expanded;
        }

        return result;
    }

    /// Expands a list of axes into raw binding combinations using Cartesian product.
    private List<Map<String, Object>> expandAxes(List<Axis<?>> axes, SamplingConfig config) {
        List<Map<String, Object>> combinations = new ArrayList<>();
        combinations.add(new HashMap<>());

        for (Axis<?> axis : axes) {
            List<?> effectiveValues = getEffectiveValues(axis, config);
            String paramName = axis.underlyingParameter().map(p -> p.name()).orElse(axis.name());
            combinations = CartesianExpander.expandAxis(combinations, paramName, effectiveValues);
        }

        return combinations;
    }

    /// Computes the maximum repetition count across all axes.
    private int computeMaxRepetitions(
            Map<String, List<Axis<?>>> axesByElement,
            List<Axis<?>> globalAxes,
            SamplingConfig config) {
        int max = 1;
        for (List<Axis<?>> elementAxes : axesByElement.values()) {
            for (Axis<?> axis : elementAxes) {
                max = Math.max(max, config.repetitions().getOrDefault(axis.name(), 1));
            }
        }
        for (Axis<?> axis : globalAxes) {
            max = Math.max(max, config.repetitions().getOrDefault(axis.name(), 1));
        }
        return max;
    }

    /// Generates trials using the original global expansion (no element targeting).
    private List<Trial> generateGlobalTrials(List<Axis<?>> sortedAxes, SamplingConfig config) {
        List<Map<String, Object>> combinations = expandAxes(sortedAxes, config);

        // Apply repetitions
        int maxRepetitions = 1;
        for (Axis<?> axis : sortedAxes) {
            int reps = config.repetitions().getOrDefault(axis.name(), 1);
            maxRepetitions = Math.max(maxRepetitions, reps);
        }

        combinations = CartesianExpander.applyRepetitions(combinations, maxRepetitions);

        // Convert raw combinations to Trial objects with Value<?> wrappers
        List<Trial> result = new ArrayList<>();
        int index = 0;
        for (Map<String, Object> rawAssignments : combinations) {
            int repetitionIndex = 0;
            if (rawAssignments.containsKey(CartesianExpander.REPETITION_KEY)) {
                repetitionIndex = ((Number) rawAssignments.get(CartesianExpander.REPETITION_KEY)).intValue();
            }

            // Wrap raw values in DefaultValue, excluding the repetition marker
            Map<String, Value<?>> assignments = new HashMap<>();
            for (Map.Entry<String, Object> entry : rawAssignments.entrySet()) {
                if (!CartesianExpander.REPETITION_KEY.equals(entry.getKey())) {
                    assignments.put(entry.getKey(), new DefaultValue<>(
                        entry.getValue(),
                        entry.getKey(),
                        Instant.now(),
                        Optional.of("Axis enumeration")
                    ));
                }
            }

            String genMethod = maxRepetitions > 1 ? "cartesian_product_rep" + repetitionIndex : "cartesian_product";
            Trial.TrialMetadata metadata = new SimpleTrialMetadata(index++, "default", genMethod, 0);
            result.add(new DefaultTrial(
                UUID.randomUUID().toString(),
                assignments,
                Collections.emptyList(),
                metadata
            ));
        }
        return result;
    }

    private List<?> getEffectiveValues(Axis<?> axis, SamplingConfig config) {
        SamplingStrategy strategy = config.strategies()
            .getOrDefault(axis.name(), SamplingStrategy.grid());
        return AxisExpander.applyStrategy(axis.values(), strategy);
    }

    private static class SimpleTrialMetadata implements Trial.TrialMetadata {
        private final int index;
        private final String group;
        private final String genMethod;
        private final int priority;

        public SimpleTrialMetadata(int index, String group, String genMethod, int priority) {
            this.index = index;
            this.group = group;
            this.genMethod = genMethod;
            this.priority = priority;
        }

        @Override public Optional<Integer> sequenceIndex() { return Optional.of(index); }
        @Override public Optional<String> group() { return Optional.ofNullable(group); }
        @Override public Optional<String> generationMethod() { return Optional.ofNullable(genMethod); }
        @Override public Optional<Integer> priority() { return Optional.of(priority); }
    }
}
